name: smlm
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pytorch
  - pip:
      - numpy>=1.26
      - pandas>=2
      - scipy>=1.14.1,!=1.15.*
      - scikit-image>=0.24
      - tifffile>=2024.8
      - PyYAML>=6
      - matplotlib>=3.8
      - seaborn>=0.13
      - Pillow>=10
      - imageio-ffmpeg>=0.5
      - jupyterlab>=4
      - nbformat>=5.10
      - spotiflow>=0.6.4.dev0,<0.7
      - cellpose>=4.1,<5
      - laptrack>=0.17,<0.18
      - saspt>=0.4
      - pytest>=8
