import os
import pandas as pd
import json
import glob

def generate_consolidated_report(output_dir="."):
    results_dir = os.path.join(output_dir, "results")
    ref_dir = os.path.join(results_dir, "ref_seq")
    quant_dir = os.path.join(results_dir, "quantification")
    stoich_dir = os.path.join(results_dir, "stoichiometry")
    reports_dir = os.path.join(results_dir, "reports")

    os.makedirs(reports_dir, exist_ok=True)
    report_path = os.path.join(reports_dir, "Automated_Summary_Report.md")

    # 1. Load Reference Info
    snp_file = os.path.join(ref_dir, "snps.json")
    snps = []
    if os.path.exists(snp_file):
        with open(snp_file, "r") as f:
            snps = json.load(f)

    # 2. Gather Quantification Results
    # Since we removed the summary CSV from the script, we aggregate here
    quant_files = glob.glob(os.path.join(quant_dir, "*_quant.csv"))
    quant_data = []
    for f in quant_files:
        df = pd.read_csv(f)
        sample = os.path.basename(f).replace("_quant.csv", "")
        total = len(df)
        b6 = len(df[df['Allele'] == 'B6'])
        cast = len(df[df['Allele'] == 'Cast'])
        ratio = cast / total if total > 0 else 0
        quant_data.append({
            "Sample": sample,
            "Total Reads": total,
            "B6": b6,
            "Cast": cast,
            "Cast Ratio": f"{ratio:.3f}"
        })
    quant_df = pd.DataFrame(quant_data)

    # 3. Gather Stoichiometry Results
    # This might still be in a summary CSV if the script outputted one to its local stoich_dir
    # However, for a standalone report, we can just print the aggregated quantification data

    # Build Markdown
    lines = [
        "# Xist SNP Analysis: Automated Summary Report",
        "",
        "This report was automatically generated from the analysis results.",
        "",
        "## 1. Reference Architecture",
        f"Amplicon mapped to genomic region defined in `target_amplicon.fa`.",
        "",
        "| SNP Index | Local Pos | B6 | Cast |",
        "| :--- | :--- | :--- | :--- |"
    ]

    for i, s in enumerate(snps):
        lines.append(f"| SNP {i+1} | {s['local_pos']} | **{s['b6']}** | **{s['cast']}** |")

    lines.extend([
        "",
        "## 2. Allele Quantification Summary",
        "",
        quant_df.to_markdown(index=False),
        "",
        "## 3. Analysis Parameters",
        "- **Data Directory**: `data/`",
        f"- **Reference**: `{os.path.join('results/ref_seq', 'target_amplicon.fa')}`",
        "- **Toolchain**: minimap2, samtools, pysam",
        "",
        "---",
        "*Report generated by Antigravity Pipeline.*"
    ])

    with open(report_path, "w") as f:
        f.write("\n".join(lines))

    print(f"Report generated: {report_path}")

if __name__ == "__main__":
    generate_consolidated_report()
